modified:   capture/d2l-capture-producer/d2l-capture-producer-editor.js
Brightspace/content-components pull request #234
Opened 2022-03-01 20:33 UTC by will-malisch

modified:   capture/d2l-capture-producer/locales/en.js
	modified:   capture/d2l-capture-producer/src/captions-utils.js
	modified:   capture/d2l-capture-producer/src/constants.js
	modified:   capture/d2l-capture-producer/src/d2l-video-producer-captions.js

2022-03-01 20:42 UTC, MichaelKovalchuk commented on capture/d2l-capture-producer/d2l-capture-producer-editor.js
> +		const mediaPlayerDuration = this._mediaPlayer?.duration;
i do not think we use this variable

2022-03-01 20:44 UTC, MichaelKovalchuk commented on capture/d2l-capture-producer/locales/en.js
> +	invalidFormat: 'HH:MM:SS.sss',
How about we us `Time must be in the following format: HH:MM:SS.sss`

2022-03-01 20:50 UTC, MarquisLP commented on capture/d2l-capture-producer/d2l-capture-producer-editor.js
> +		this._mediaPlayer = this.shadowRoot.querySelector('d2l-labs-media-player'); // why is this variable getting a this. call, when it is not a property of the class
> why is this variable getting a this. call, when it is not a property of the class

So in LitElement, a component is allowed to have variables assigned to `this` even if they're not declared as a property in `static get properties()`. In this case, `this._mediaPlayer` is just a normal private variable that can be accessed from within the component. Meanwhile, the properties in `static get properties()` are used by LitElement to determine when to re-render.

2022-03-01 20:56 UTC, MarquisLP commented on capture/d2l-capture-producer/d2l-capture-producer-editor.js
> +		// this.shadowRoot.querySelector('d2l-video-producer-captions').mediaPlayerDuration = this._mediaPlayer.duration;
Minor: looks like a temporary line for testing that was accidentally kept in.

2022-03-01 21:01 UTC, MarquisLP commented on capture/d2l-capture-producer/d2l-capture-producer-editor.js
> +		const mediaPlayerDuration = this._mediaPlayer?.duration;
Yeah, looks like it was meant to be used on line 257.

2022-03-01 21:18 UTC, MarquisLP commented on capture/d2l-capture-producer/src/d2l-video-producer-captions.js
> +
Doesn't seem like this function is used anywhere.

2022-03-02 15:01 UTC, will-malisch commented on capture/d2l-capture-producer/d2l-capture-producer-editor.js
> +		this._mediaPlayer = this.shadowRoot.querySelector('d2l-labs-media-player'); // why is this variable getting a this. call, when it is not a property of the class
Oh nevermind, I see whats going on here, I didn't realize that I left "why is this variable getting a this. call, when it is not a property of the class" as a comment, my bad.

2022-03-02 21:59 UTC, MarquisLP requested changes

2022-03-02 21:59 UTC, MarquisLP commented on capture/d2l-capture-producer/src/d2l-video-producer-captions.js
> +	}
It's good that you're using the same event-driven approach for updating the timestamp to keep things consistent! However, using `captions-cue-start/end-timestamp-synced` for both the "Sync to timeline" button and manual timestamp text edits results in a few issues:

- The "synced" in the event name means "synced to timeline position", so the name is misleading when it's used to describe manual timestamp edits via text.
- It adds complexity, as we now need to distinguish between instances of this event that were fired from the "Sync" buttons, and instances that were fired from the timestamp text input. This makes [the event handlers](https://github.com/Brightspace/content-components/blob/d36ef5a3bb2c36f1c6c9816926b8788d00d5f794/capture/d2l-capture-producer/d2l-capture-producer-editor.js#L925) in `d2l-capture-producer-editor.js` more complex as well.

Because of that, I think it would be preferable to **make a new event type** (named something like `captions-cue-start/end-timestamp-edited`) and add new event handlers for them in `d2l-capture-producer-editor.js`.  
`_handleSyncStart/EndTimestampFocusout()` would fire this new event type, while `_handleSyncStart/EndTimestampClicked()` would remain as-is and fire `captions-cue-start/end-timestamp-synced`.

2022-03-02 21:59 UTC, MarquisLP commented on capture/d2l-capture-producer/src/captions-utils.js
> +	const format = /[0-9][0-9]:[0-9][0-9]:[0-9][0-9](\.[0-9][0-9][0-9]|\.[0-9][0-9]|\.[0-9]|\.|)$/;
It may be possible to shorten this regex and reduce repetition. Some resources:

- https://www.regextutorial.org/regex-for-numbers-and-ranges.php
- https://stackoverflow.com/questions/37194527/how-do-i-repeat-regex

2022-03-02 21:59 UTC, MarquisLP commented on capture/d2l-capture-producer/test/captions-utils.test.js
> +	describe('validTimestampFormat', () => {
Nice job covering all these cases! Can we add a few more for these edge cases:

- Empty string
- Garbage text that doesn't resemble the format at all (e.g. "asdfghjkl123")

2022-03-02 21:59 UTC, MarquisLP commented on capture/d2l-capture-producer/src/d2l-video-producer-captions.js
> +			: null;
Would it be possible to put the tooltip around the timestamp text box itself, instead of this new icon? From what I've seen on various sites, having the error tooltip attached to the textbox is the usual behaviour. The `<d2l-tooltip>` docs show this as an example:

<img src="https://github.com/BrightspaceUI/core/raw/main/components/tooltip/screenshots/tooltip-error.png"></img>

2022-03-02 22:07 UTC, MarquisLP commented
Some more things that Will and I noticed that should be fixed/addressed:

- In certain cases, the Start/End timestamps will revert back to their original value when losing focus. Since we're using the "?" icon with tooltip approach, we shouldn't be reverting the timestamp values (except possibly when saving -- see the next point).
- If the user Saves or Finishes when there are errors in 1 or more timestamps, those timestamp values don't get reverted back to their original value in the UI. This technically isn't a critical issue, as the original values are what actually get saved, but it might mislead users into thinking that the errors got saved.

2022-03-02 22:12 UTC, MarquisLP commented on capture/d2l-capture-producer/src/d2l-video-producer-captions.js
> +			: null;
Discussed this with Will and we decided to stay with the "?" icon + tooltip approach. If we were to put the tooltip on the textbox and have it automatically disappear, then the user might never get to see the tooltip (e.g. if they scroll down to another cue off-screen and change focus to that cue).

2022-03-03 21:06 UTC, MarquisLP approved these changes
LGTM! Just had a few minor comments.

2022-03-03 21:06 UTC, MarquisLP commented on capture/d2l-capture-producer/src/d2l-video-producer-captions.js
> +		</div>
Looks like the indentation got mixed up here 😅 Can you add back the indentation?

2022-03-03 21:06 UTC, MarquisLP commented on capture/d2l-capture-producer/src/d2l-video-producer-captions.js
>  			}
Were you able to shrink the width of the timestamp text input?

2022-03-04 15:51 UTC, will-malisch commented on capture/d2l-capture-producer/d2l-capture-producer-editor.js
> +	_handleChangeCaptionsCueEndTimestampByTextInput(event) {
Will do.

2022-03-04 16:39 UTC, will-malisch commented on capture/d2l-capture-producer/src/d2l-video-producer-captions.js
>  			}
Yes, I centered it and reduced this width a touch

2022-03-04 16:41 UTC, will-malisch commented on capture/d2l-capture-producer/src/d2l-video-producer-captions.js
> +		</div>
fixed

2022-03-04 16:41 UTC, will-malisch commented on capture/d2l-capture-producer/src/captions-utils.js
> +	const format = /([\d]{2}:){2}[\d]{2}(\.[\d]{3}|\.[\d]{2}|\.[\d]|\.|)$/;
thanks!

2022-03-04 16:41 UTC, will-malisch commented on capture/d2l-capture-producer/d2l-capture-producer.js
> +				this._captionsLoading = true;
fixed

2022-03-04 17:04 UTC, will-malisch commented on capture/d2l-capture-producer/d2l-capture-producer-editor.js
> +	_handleChangeCaptionsCueEndTimestampByTextInput(event) {
Done.

2022-03-04 17:18 UTC, MarquisLP approved these changes
Looks ready to me! I just had one minor comment for refactoring the code a little bit. Once you push a fix for that, you can feel free to go ahead and merge.

2022-03-04 17:18 UTC, MarquisLP commented on capture/d2l-capture-producer/d2l-capture-producer-editor.js
> +			}
Looks good! I think we can condense this a bit further and remove the if-else blocks, as both blocks are pretty similar.

```
const newEndTime = event.detail.newEndTime ?? this._mediaPlayer.currentTime
editedCue.endTime = Math.floor(newEndTime * 1000) / 1000;
...
```

2022-03-04 17:18 UTC, MarquisLP commented on capture/d2l-capture-producer/d2l-capture-producer.js
> +				this._captionsLoading = true; // Force the captions tab to reload in order to reset any invalid timestamp text inputs.
👍

2022-03-04 17:18 UTC, MarquisLP commented on capture/d2l-capture-producer/src/d2l-video-producer-captions.js
>  			}
Nice, looks like this will work. Just so Michael and I can see what this looks like now, can you post a screenshot?

2022-03-04 17:39 UTC, will-malisch commented on capture/d2l-capture-producer/src/d2l-video-producer-captions.js
>  			}
<img width="1201" alt="Screen Shot 2022-03-04 at 12 39 20 PM" src="https://user-images.githubusercontent.com/99415792/156814014-79901162-305d-4385-9d57-cd0c9ab0509d.png">

2022-03-04 17:40 UTC, will-malisch commented on capture/d2l-capture-producer/src/d2l-video-producer-captions.js
>  			}
hows that?

2022-03-04 17:42 UTC, MarquisLP commented on capture/d2l-capture-producer/src/d2l-video-producer-captions.js
>  			}
Looks good! It matches the original positioning quite closely, which is nice.

2022-03-04 17:42 UTC, will-malisch commented on capture/d2l-capture-producer/d2l-capture-producer-editor.js
> +			}
Okay

2022-03-04 17:48 UTC, will-malisch commented on capture/d2l-capture-producer/src/d2l-video-producer-captions.js
>  			}
Sweet, thanks

2022-03-04 17:50 UTC, MarquisLP approved these changes
LGTM, ready to merge 👍

2022-03-04 17:52 UTC, merged