Separate control button from the timeline
Brightspace/content-components pull request #283
Opened 2022-04-01 17:51 UTC by lchan131

2022-04-01 18:08 UTC, rcausey commented on capture/d2l-capture-producer/src/d2l-capture-producer-timeline.js
> +				<d2l-video-producer-timeline-controls
This component looks good, but there's a problem here in that if you wanted to move this component to a different location (e.g. to the left side of the timeline, or above/below), you'd also have to modify the `_updateRelativeWidth` function, which I'd like to avoid. Basically, I'd like the timeline canvas and these buttons to not be dependent on each other.

I think if you just rip this component out of here and put it in the editor component next to the timeline, that should work. Then you can modify the width sizing code in here to not be dependent on these controls.

2022-04-04 18:13 UTC, lchan131 commented on capture/d2l-capture-producer/src/d2l-capture-producer-timeline.js
> +				<d2l-video-producer-timeline-controls
Okay. I've done what you suggested with some additional changes:

The `width` property has been removed from timeline component. It looks at the width of the parent and takes that width instead. To set the width, change the CSS attribute.

2022-04-04 18:17 UTC, rcausey commented
Looks good to me. Just want @MarquisLP to take a look too, since he's worked a lot with Producer.

2022-04-04 18:18 UTC, rcausey approved these changes
Looks good, but wait for @MarquisLP to approve before merging.

2022-04-04 18:40 UTC, MarquisLP commented
Yup, taking a look now.

2022-04-04 19:36 UTC, MarquisLP requested changes
Code looks good for the most part. I have a few questions and small suggestions, but they're nothing major.

However, I just tested this branch on my local LE, and I've encountered a few issues:

- Clicking on the timeline does nothing in all 3 modes (can't seek, mark, or cut).
- For audio files, the captions tab gets stuck loading.

Adding chapters and captions works fine, though.

Not sure if this is just something wrong with my local LE, so can you check on your local LE as well @lchan131?

2022-04-04 19:36 UTC, MarquisLP commented on capture/d2l-capture-producer/src/d2l-capture-producer-timeline.js
> +		this._widthPixels = rootWidth - 2;
Where does the minus 2 come from? It's quite different from `controlButtonWidth` from the previous code.

2022-04-04 19:41 UTC, lchan131 commented on capture/d2l-capture-producer/src/d2l-capture-producer-timeline.js
> +			controlMode: { type: String },
Good catch. The one in editor is supposed to be a string

2022-04-04 19:47 UTC, MarquisLP commented on capture/d2l-capture-producer/src/d2l-capture-producer-timeline.js
> +			controlMode: { type: String },
I see, hopefully fixing that will resolve the timeline issue I encountered.

2022-04-04 20:06 UTC, lchan131 commented on capture/d2l-capture-producer/src/d2l-capture-producer-timeline.js
> +		this._widthPixels = rootWidth - 2;
I can remove the -2. In some of my iterations, the -2 is required for some reason, because it caused the timeline to slowly expand.

2022-04-04 20:06 UTC, lchan131 commented on capture/d2l-capture-producer/d2l-capture-producer-editor.js
> +			}
Yes

2022-04-04 20:15 UTC, lchan131 commented
> However, I just tested this branch on my local LE, and I've encountered a few issues:
> 
> * Clicking on the timeline does nothing in all 3 modes (can't seek, mark, or cut).
> * For audio files, the captions tab gets stuck loading.
> 
> Adding chapters and captions works fine, though.
> 
> Not sure if this is just something wrong with my local LE, so can you check on your local LE as well @lchan131?

The 3 modes work for me locally so it might just be your local setup.
As for the captions stuck for audio files, I am also getting that. I will look into fixing that.

2022-04-04 20:20 UTC, MarquisLP commented
> The 3 modes work for me locally so it might just be your local setup.
As for the captions stuck for audio files, I am also getting that. I will look into fixing that.

Thanks for checking. I haven't run `full_all` in at least 2 weeks, so I'll run it now and check the changes in this PR again tomorrow morning.

2022-04-04 21:34 UTC, lchan131 commented
> However, I just tested this branch on my local LE, and I've encountered a few issues:
> 
> * Clicking on the timeline does nothing in all 3 modes (can't seek, mark, or cut).
> * For audio files, the captions tab gets stuck loading.

Regarding the captions getting stuck on loading, it looks like this is also the case before I even worked on the timeline. Can someone check if this is true for their local as well?

2022-04-05 13:27 UTC, MarquisLP commented
> Regarding the captions getting stuck on loading, it looks like this is also the case before I even worked on the timeline. Can someone check if this is true for their local as well?

I've checked on Staging, which is up-to-date with master, and can confirm that the audio captions issue is happening there as well.

The timeline issue is still occurring for me, so once my full_all finishes updating to the latest LE code, I'll check both issues on my local.

2022-04-05 17:57 UTC, MarquisLP commented
Lennard and I have confirmed that the timeline issue was related to using an outdated BSI version. Once I brought my BSI up-to-date with the main branch, the timeline started working as expected.

@MichaelKovalchuk was running into this issue as well, so once he confirms this on his local as well, we can merge this PR.

2022-04-05 18:28 UTC, MarquisLP commented on capture/d2l-capture-producer/d2l-capture-producer-editor.js
> +		console.log('editor constructor')
Looks like this was an accidental commit?

2022-04-05 18:44 UTC, lchan131 commented on capture/d2l-capture-producer/d2l-capture-producer-editor.js
> +		console.log('editor constructor')
Yes this is an accident. I will revert this

2022-04-05 20:31 UTC, lchan131 commented
> Lennard and I have confirmed that the timeline issue was related to using an outdated BSI version. Once I brought my BSI up-to-date with the main branch, the timeline started working as expected.
> 
> @MichaelKovalchuk was running into this issue as well, so once he confirms this on his local as well, we can merge this PR.
> 
> I have also confirmed that the audio issue is fixed after the latest commits.

I've confirmed with Michael that this has been resolved for him too. I will merge.

2022-04-05 20:32 UTC, MarquisLP approved these changes

2022-04-05 20:32 UTC, merged