content selector component
Brightspace/content-components pull request #320
Opened 2022-05-18 17:50 UTC by lchan131

2022-05-25 21:52 UTC, rcausey commented
This looks good, but I'm thinking it might be better if we extracted the buttons out of the individual components and implemented them inside of `d2l-content-selector` instead. This would make the individual components more flexible and re-useable outside of a dialog. Would this be a lot of work to change?

2022-05-26 14:00 UTC, lchan131 commented
> This looks good, but I'm thinking it might be better if we extracted the buttons out of the individual components and implemented them inside of `d2l-content-selector` instead. This would make the individual components more flexible and re-useable outside of a dialog. Would this be a lot of work to change?

No this would be easy to do. I'll work on it

2022-05-26 20:05 UTC, rcausey requested changes
In general, this looks really good. Most of my comments are just because I've changed my mind from the initial spec and want to keep this as simple as possible until we need those other options.

2022-05-26 20:05 UTC, rcausey commented on core/d2l-content-selector/d2l-content-selector.js
> +			allowExistingObjectSelection: { type: Boolean },
Same as other comments - I think we should remove this `allowExistingObjectSelection` for now and just default to the behaviour in the SCORM dialog

2022-05-26 20:05 UTC, rcausey commented on core/d2l-content-selector/d2l-content-selector.js
> +		if (this.autoSelectAfterUpload) {
Should be removed

2022-05-26 20:05 UTC, rcausey commented on core/d2l-content-selector/d2l-content-selector.js
> +		this._openPreview();
I don't think openPreview should be done here anymore

2022-05-26 20:05 UTC, rcausey commented on core/d2l-content-selector/d2l-content-selector.js
> +		if (this.editPropertiesAfterUpload) {
Default to SCORM dialog behaviour here instead of using these options

2022-05-26 20:05 UTC, rcausey commented on core/d2l-content-topic-settings/d2l-content-topic-settings.js
> +		this.resourceType = '';
See other comments in other component about changing this from resourceType to revisionTag and determining resourceType from the revision

2022-05-27 14:12 UTC, lchan131 commented on core/d2l-content-selector/d2l-content-selector.js
> +		this._openPreview();
The _openPreview function only emits an event, so I think it should stay.

2022-05-30 15:17 UTC, rcausey approved these changes
Looks good, just look into my comments before merging

2022-05-30 15:17 UTC, rcausey commented on core/d2l-content-topic-settings/d2l-content-topic-settings.js
> +		.wrapper {
I think this wrapper shouldn't be necessary in here since we moved the buttons outside of the component, right?

2022-05-30 15:17 UTC, rcausey commented on core/d2l-content-topic-settings/d2l-content-topic-settings.js
> +		console.log(revision);
Console log

2022-05-30 15:17 UTC, rcausey commented on core/d2l-content-topic-settings/d2l-content-topic-settings.js
> +			<div class="wrapper">
See comment above re: wrapper

2022-05-30 15:17 UTC, rcausey commented on core/d2l-content-properties/demo/index.html
> +					d2lrn="d2l:brightspace:content:region:97dc5895-cd3b-465f-8d5b-3c8d7e1bb6a7:scorm:0"
Doesn't really matter, but just curious why you changed the contentId from a GUID to a number?

2022-05-30 15:17 UTC, rcausey commented on core/d2l-content-properties/d2l-content-properties.js
> +		.settings-container {
Let's move this margin out of the component and into the selector instead

2022-05-30 15:17 UTC, rcausey commented on core/d2l-content-selector/d2l-content-selector.js
> +		this.allowExistingObjectSelection = true;
Let's get rid of `allowExistingObjectSelection` for now

2022-05-30 15:17 UTC, rcausey commented on core/d2l-content-selector/d2l-content-selector.js
> +		if (this.allowUpload && !this.allowExistingObjectSelection) {
See above comment on `allowExistingObjectSelection` - shouldn't need this after removal

2022-05-30 15:46 UTC, lchan131 commented on core/d2l-content-topic-settings/d2l-content-topic-settings.js
> +			<div class="wrapper">
Again, this is necessary for the demo

2022-05-30 15:48 UTC, lchan131 commented on core/d2l-content-properties/demo/index.html
> +					d2lrn="d2l:brightspace:content:region:97dc5895-cd3b-465f-8d5b-3c8d7e1bb6a7:scorm:0"
I just figured it would be easier in the future if we wanted to add a new type, for instance.

2022-05-30 15:50 UTC, lchan131 commented on core/d2l-content-properties/d2l-content-properties.js
> +		.settings-container {
Alright. I'll do this for the wrapper classes discussed above as well.

2022-05-30 16:23 UTC, merged